# Automatic movement of labeled issues to specific column.

name: Project Columns Automation

on:
  issues:
    types: [labeled]

jobs:
  track_enhancements:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      name: Issue to Enhancement Tracker
      if: github.event.label.name == 'enhancement'
      with:
        action-token: "${{ secrets.AUTOMATION_TOKEN }}"
        project-url: "https://github.com/aareid10/github-automate/projects/1"
        column-name: "To Do"
        label-name: "enhancement"
        columns-to-ignore: "Done"
  track_refactors:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      name: Issue to Refactor Tracker
      if: github.event.label.name == 'refactor'
      with:
        action-token: "${{ secrets.AUTOMATION_TOKEN }}"
        project-url: "https://github.com/aareid10/github-automate/projects/1"
        column-name: "Refactors"
        label-name: "refactor"
        columns-to-ignore: "To Do,Done"
  track_stalled:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      name: Issue to Stalled Tracker
      if: github.event.label.name == 'stalled'
      with:
        action-token: "${{ secrets.AUTOMATION_TOKEN }}"
        project-url: "https://github.com/aareid10/github-automate/projects/1"
        column-name: "Stalled"
        label-name: "stalled"
        columns-to-ignore: "To Do,Done"
  track_bugs:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      name: Issue to Bug Tracker
      if: github.event.label.name == 'bug'
      with:
        action-token: "${{ secrets.AUTOMATION_TOKEN }}"
        project-url: "https://github.com/aareid10/github-automate/projects/1"
        column-name: "Bugs"
        label-name: "bug"
        columns-to-ignore: "To Do,Done"
