# Automatic documentation of source code.

name: Project Documentation Automation

on:
  push:
    branches:
      - main
      - master

jobs:
  issues_Enhancement:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: check dir
          run: pwd
        - name: check files
          run: ls
        - name: document js source
          run: ./documentation.sh
        - name: setup git config
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
        - name: commit
          run: |
            git add . --all
            git commit -m "auto doc action"
            git push origin master
