# Automatic documentation of source code.

name: Project Documentation Automation

on:
  push:
    branches:
      - main
      - master

jobs:
  issues_Enhancement:
      runs-on: ubuntu-latest
      steps:
        - name: check dir
          run: pwd
        - name: check files
          run: ls
        - name: document js source
          run: ./documentation.sh
