# Automatic documentation of source code.

name: Project Documentation Automation

on:
  push:
    branches:
      - main
      - master

jobs:
  issues_Enhancement:
      runs-on: ubuntu-latest
      steps:
        run: |
        sh ./documentation.sh
