# This is a basic workflow to help you get started with Actions

name: AUTOMATION_PROJECT_ISSUES

on:
  push:
    branches:
      - main
      - master
      - 'releases/*'

jobs:
  issue_gen_bugs:
    runs-on: ubuntu-latest
    steps:
      - if: "contains(github.event.head_commit.message, '[bug]')"
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
        with:
          filename: .github/issues.bugs.md
