# This is a basic workflow to help you get started with Actions

name: AUTOMATION_PROJECT_ISSUES

on:
  push:
    branches:
      - main
      - master
      - 'releases/*'

jobs:
  issue_gen_bugs_skip:
    runs-on: ubuntu-latest
    steps:
      - if: "! contains(github.event.head_commit.message, '[bug]')"
        run: echo "skipping bug label"
    
  issue_gen_bugs:
    runs-on: ubuntu-latest
    steps:
    - uses: nashmaniac/create-issue-action@v1.1
      name: Create Bug Issue
      if: "contains(github.event.head_commit.message, '[bug]')"
      with:
        title: ${{github.event.head_commit.message}}
        token: ${{secrets.AUTOMATION_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: Found by ${{github.actor}} in ${{github.sha}}
    
  
