# Automatic creation of labeled issues based on commits.

name: Project Issues Automation

on:
  push:
    branches:
      - main
      - master

jobs:
  issues_enhancement:
      runs-on: ubuntu-latest
      steps:
      - uses: nashmaniac/create-issue-action@v1.1
        name: Enhancement Issue
        if: "contains(github.event.head_commit.message, '[enhance]')"
        with:
          title: ${{github.event.head_commit.message}}
          token: ${{secrets.AUTOMATION_TOKEN}}
          assignees: ${{github.actor}}
          labels: enhancement
          body: Proposed by ${{github.actor}} in ${{github.sha}}
  issues_refactors:
    runs-on: ubuntu-latest
    steps:
    - uses: nashmaniac/create-issue-action@v1.1
      name: Refactor Issue
      if: "contains(github.event.head_commit.message, '[refactor]')"
      with:
        title: ${{github.event.head_commit.message}}
        token: ${{secrets.AUTOMATION_TOKEN}}
        assignees: ${{github.actor}}
        labels: refactor
        body: Proposed by ${{github.actor}} in ${{github.sha}}
  issues_stalled:
    runs-on: ubuntu-latest
    steps:
    - uses: nashmaniac/create-issue-action@v1.1
      name: Stalled Issue
      if: "contains(github.event.head_commit.message, '[stalled]')"
      with:
        title: ${{github.event.head_commit.message}}
        token: ${{secrets.AUTOMATION_TOKEN}}
        assignees: ${{github.actor}}
        labels: stalled
        body: Noted by ${{github.actor}} in ${{github.sha}}
  issues_bugs:
    runs-on: ubuntu-latest
    steps:
    - uses: nashmaniac/create-issue-action@v1.1
      name: Bug Issue
      if: "contains(github.event.head_commit.message, '[bug]')"
      with:
        title: ${{github.event.head_commit.message}}
        token: ${{secrets.AUTOMATION_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: Found by ${{github.actor}} in ${{github.sha}}
